// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function ExportReport(arg1:string):Promise<string>;

export function GetConfig(arg1:string):Promise<Record<string, string>>;

export function GetRealtimeOPS(arg1:string):Promise<number>;

export function GetReport(arg1:string):Promise<model.AnalysisReport>;

export function GetServerInfo(arg1:string):Promise<Record<string, string>>;

export function GetSlowLog(arg1:string):Promise<Array<model.SlowLogEntry>>;

export function ListConnections():Promise<Array<model.ConnectionProfile>>;

export function ListReports():Promise<Array<model.ReportSummary>>;

export function RunAnalysis(arg1:string):Promise<model.AnalysisReport>;

export function SaveConnection(arg1:model.ConnectionProfile):Promise<model.ConnectionProfile>;

export function TestConnection(arg1:model.ConnectionProfile):Promise<model.ConnectionTestResult>;
