// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetRealtimeOPS(arg1) {
  return window['go']['main']['App']['GetRealtimeOPS'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetSlowLog(arg1) {
  return window['go']['main']['App']['GetSlowLog'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function RunAnalysis(arg1) {
  return window['go']['main']['App']['RunAnalysis'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
